# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - elo-vet-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Gradle (Skipping Tests)
        run: |
          chmod +x gradlew
          ./gradlew build -x test

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          # O Gradle salva o arquivo .jar na pasta build/libs/ (diferente do Maven)
          path: '${{ github.workspace }}/build/libs/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          # Certifique-se de que esses secrets existem no novo repositório Elo Vet!
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F82BAEF4141647199EE2C7D63E5077DB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0B282A7B7C994E17A0A5CFE2259FA29D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7DF866885F304A2E9078887F8BC12616 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'api-java-seurm' # Confirme se o nome do App Service na Azure é esse mesmo
          slot-name: 'Production'
          package: '*.jar'
